# Agenda

1. Data structures
    - Built-in data structures, and how they work
    - Alternatives to these in the standard library
    - The `collections` modules -- variations on dictionaries
2. Functions
3. Functional programming
4. Modules and packages
5. Objects
6. Iterators and generators
7. Decorators
8. Concurrency

# gitautopush

It's a package on PyPI

You can install it with

```
pip install gitautopush
```

Then just run it in a directory:

```
gitautopush .
```

Every minute or so, it checks if any files have changed. If so, it runs `git commit -a` and then `git push`.

# Data structures -- builtin data structures

# `None`

There are no variable declarations in Python! 

In [1]:
# in assignment, the right side runs before the left side

x = 100   # creates the x variable, and then assigns 100 to it
type(x)

int

In [2]:
x = 'abcd'  # x already exists, but now we assign 'abcd' to it
type(x)

str

In [3]:
x = None
type(x)

NoneType

In [4]:
# how can I check if x is None?

if x == None:   # unfortunately, this works! -- this code is un-Pythonic
    print('Yes, it is None!')

Yes, it is None!


# Comparing with `None`

`None` is a singleton -- no matter how many instances you think you've created, there's only one instance of `None` in all of Python.

PEP8 tells us that if we're comparing with a singleton, we should not use `==`.  Rather, we should use `is`.

- `==` asks: Are the two objects equivalent in value?
- `is` asks: Are these two objects the same object?

`is` compares the object IDs.


In [6]:
id(x)  # this number is the address in memory of the object that x is referring to

4481073152

In [7]:
y = None
id(y)

4481073152

In [8]:
# since id(x) and id(y) are the same, they must be two names referring to the same object
# thus, they are not only ==, but they are is:

x is y

True

In [9]:
x = [10, 20, 30]  # I've created a list
y = [10, 20, 30]  # I've created another list

# both of these lists have the same values. But they are *not* the same list in memory.
# they're two separate objects, two instances of "list"

# in the case of a Singleton object, there is only one instance.
# each time you try to create a new instance, you just get a copy of the existing one.

type(None)

NoneType

In [10]:
x = type(None)()   # creating a new instance of None
y = type(None)()   # creating a new instance of None

In [11]:
id(x)

4481073152

In [12]:
id(y)

4481073152

In [13]:
x is y

True

# `None` vs. `NaN` vs. other similar things



In [14]:
import numpy as np
import pandas as pd

In [15]:
type(np.nan)

float

In [17]:
type(np.NaN)

float

In [18]:
# can I compare None to itself?
None == None

True

In [19]:
None is None

True

In [23]:
# are these objects' at the same location in memory -- i.e., are they exactly the same object?
np.nan is np.nan

True

In [24]:
# is np.nan's value equal to itself...

# nan is a float that isn't equal to itself!
np.nan == np.nan

False

In [27]:
# this is new in Pandas, and it's supposed to (eventually) take over from np.nan
# it'll work with the new pandas string types and other types
pd.NA

<NA>

In [28]:
# np.isnan # this checks if something is equal to nan, *not* using == 

a = np.array([10, 20, 30, np.nan, 50, 60])
a

array([10., 20., 30., nan, 50., 60.])

In [29]:
a[a==np.nan]

array([], dtype=float64)

In [30]:
np.isnan(a)

array([False, False, False,  True, False, False])

In [31]:
a[np.isnan(a)]

array([nan])

In [32]:
a[~np.isnan(a)]

array([10., 20., 30., 50., 60.])

In [33]:
x = 100
y = 100

x == y  

True

In [34]:
x is y

True

In [35]:
x = 100_000   # _ is ignored in numbers!
y = 100_000

x == y

True

In [36]:
x is y

False

# What's going on?

Python knows we're going to use small numbers a lot. So instead of creating new integer objects each time we need a small number (from -5 to 256), it uses already-allocated numbers.