# Agenda

1. Data structures
    - Built-in data structures, and how they work
    - Alternatives to these in the standard library
    - The `collections` modules -- variations on dictionaries
2. Functions
3. Functional programming
4. Modules and packages
5. Objects
6. Iterators and generators
7. Decorators
8. Concurrency

# gitautopush

It's a package on PyPI

You can install it with

```
pip install gitautopush
```

Then just run it in a directory:

```
gitautopush .
```

Every minute or so, it checks if any files have changed. If so, it runs `git commit -a` and then `git push`.

# Data structures -- builtin data structures

# `None`

There are no variable declarations in Python! 

In [1]:
# in assignment, the right side runs before the left side

x = 100   # creates the x variable, and then assigns 100 to it
type(x)

int

In [2]:
x = 'abcd'  # x already exists, but now we assign 'abcd' to it
type(x)

str

In [3]:
x = None
type(x)

NoneType

In [4]:
# how can I check if x is None?

if x == None:   # unfortunately, this works! -- this code is un-Pythonic
    print('Yes, it is None!')

Yes, it is None!


# Comparing with `None`

`None` is a singleton -- no matter how many instances you think you've created, there's only one instance of `None` in all of Python.

PEP8 tells us that if we're comparing with a singleton, we should not use `==`.  Rather, we should use `is`.

- `==` asks: Are the two objects equivalent in value?
- `is` asks: Are these two objects the same object?

`is` compares the object IDs.


In [6]:
id(x)  # this number is the address in memory of the object that x is referring to

4481073152

In [7]:
y = None
id(y)

4481073152

In [8]:
# since id(x) and id(y) are the same, they must be two names referring to the same object
# thus, they are not only ==, but they are is:

x is y

True

In [9]:
x = [10, 20, 30]  # I've created a list
y = [10, 20, 30]  # I've created another list

# both of these lists have the same values. But they are *not* the same list in memory.
# they're two separate objects, two instances of "list"

# in the case of a Singleton object, there is only one instance.
# each time you try to create a new instance, you just get a copy of the existing one.

type(None)

NoneType

In [10]:
x = type(None)()   # creating a new instance of None
y = type(None)()   # creating a new instance of None

In [11]:
id(x)

4481073152

In [12]:
id(y)

4481073152

In [13]:
x is y

True

# `None` vs. `NaN` vs. other similar things



In [14]:
import numpy as np
import pandas as pd

In [15]:
type(np.nan)  # "not a number"

float

In [17]:
type(np.NaN)

float

In [18]:
# can I compare None to itself?
None == None

True

In [19]:
None is None

True

In [23]:
# are these objects' at the same location in memory -- i.e., are they exactly the same object?
np.nan is np.nan

True

In [24]:
# is np.nan's value equal to itself...

# nan is a float that isn't equal to itself!
np.nan == np.nan

False

In [27]:
# this is new in Pandas, and it's supposed to (eventually) take over from np.nan
# it'll work with the new pandas string types and other types
pd.NA

<NA>

In [28]:
# np.isnan # this checks if something is equal to nan, *not* using == 

a = np.array([10, 20, 30, np.nan, 50, 60])
a

array([10., 20., 30., nan, 50., 60.])

In [29]:
a[a==np.nan]

array([], dtype=float64)

In [30]:
np.isnan(a)

array([False, False, False,  True, False, False])

In [31]:
a[np.isnan(a)]

array([nan])

In [32]:
a[~np.isnan(a)]

array([10., 20., 30., 50., 60.])

In [33]:
x = 100
y = 100

x == y  

True

In [34]:
x is y

True

In [35]:
x = 100_000   # _ is ignored in numbers!
y = 100_000

x == y

True

In [36]:
# "x is y " == "id(x) == id(y)"
x is y     # this is asking: are x and y the same object in memory

False

# What's going on?

Python knows we're going to use small numbers a lot. So instead of creating new integer objects each time we need a small number (from -5 to 256), it uses already-allocated numbers.

In [37]:
id(x)

5197268848

In [38]:
id(y)

5197268784

In [39]:
# what about "is" and strings?

x = 'abcd'
y = 'abcd'

x == y

True

In [40]:
x is y

True

In [41]:
x = 'abcd' * 100_000
y = 'abcd' * 100_000

x == y 

True

In [42]:
x is y

False

In [43]:
x = 'a.cd'
y = 'a.cd'

x == y

True

In [44]:
# we're not asking if x's value and y's value are the same
# we're asking: are x and y referring to the same object in memory?
x is y

False

# Python doesn't really have variables!

When you assign `x = 'abcd'`, Python takes the string value `abcd`, and assigns it to a dictionary. What's the key in the dictionary? The string `x`!

So it needs to create a new string, `'x'`, each time we store to or retrieve from the variable `x`.  That's a lot of strings we're going to create.

So Python doesn't.  Rather, it caches our strings.

- Any string that's short enough (I think shorter than 1,000 characters)
- And that only contains valid identifier (variable/function) characters -- letters, `_`, and numbers


In [45]:
x = [10, 20, 30]
y = x

x is y

True

In [46]:
import copy
y = copy.copy(x)  # this copies only the top layer

y

[10, 20, 30]

In [47]:
x is y

False

In [48]:
import copy
y = copy.deepcopy(x)  # this copies all layers, all the way down

y

[10, 20, 30]

In [49]:
x = 100
y = x

x = 200
y  # what's the value of y?

100

In [50]:
import copy

x = [[100, 200], [300, 400], [500, 600]]
y = copy.copy(x)

x[0][1] = '!'
y

[[100, '!'], [300, 400], [500, 600]]

In [51]:
id(x)

5197955904

In [52]:
id(y)

5189378560

In [53]:
id(x[0])

5197625408

In [54]:
id(y[0])

5197625408

In [55]:
y = x  # both x and y are referring to the same object

# Numbers!

In [57]:
# how much memory does an integer take up in Python?

import sys

x = 0
sys.getsizeof(x)  # how big, in *bytes*, is x?

24

In [58]:
x = 1
sys.getsizeof(x)

28

In [59]:
# what's the largest int we can have in Python?
# it's limited by how much memory is in your system.

x = 100_000_000_000_000
x

100000000000000

In [60]:
x = x ** 12345

In [62]:
sys.getsizeof(x)

76576

In [63]:
# floats?

x = 1.0
type(x)

float

In [64]:
0.1 + 0.2

0.30000000000000004

In [65]:
1/3  # cannot be represented by a terminating decimal

0.3333333333333333

# How can we solve this problem?

1. Use NumPy or Pandas, which uses float implemented in C, where you can choose a large number of bits (so the error becomes so tiny, it's ignored)
2. Use integers, just call it 1000 * cents, for example.
3. Use Python's `round` function.  For example: `round(0.1 + 0.2, 2)`
4. Use the `Decimal` class in the `decimal` module, aka BCD -- binary coded decimals.

In [67]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=np.float16)

In [68]:
a

array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=float16)

In [69]:
a + 0.1

array([0.2   , 0.2998, 0.4   , 0.5   , 0.6   ], dtype=float16)

In [70]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=np.float128)   # 128-bit float, so the error is so tiny, it disappears

In [71]:
a + 0.1

array([0.2, 0.3, 0.4, 0.5, 0.6], dtype=float128)

In [72]:
round(0.1 + 0.2, 2)

0.3

In [74]:
from decimal import Decimal

# advantage: very accurate
# disadvantage: very high memory use, very slow

x = Decimal('0.1')  # creating a new Decimal object based on the string '0.1'
y = Decimal('0.2')  # same, with '0.2'

x + y

Decimal('0.3')

In [ ]:
# 01 would be -- 0b00 0b01

In [75]:
# don't do this!

x = Decimal(0.1) 
y = Decimal(0.2) 

x + y

Decimal('0.3000000000000000166533453694')

In [76]:
x

Decimal('0.1000000000000000055511151231257827021181583404541015625')

In [77]:
y

Decimal('0.200000000000000011102230246251565404236316680908203125')

In [78]:
a

array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=float128)

In [79]:
np.float

/var/folders/rr/0mnyyv811fs5vyp22gf4fxk00000gn/T/ipykernel_72890/699376334.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float


float

In [81]:
np.float128(0.1) + np.float128(0.2)

0.30000000000000001665

# Strings

Strings are immutable, and contain Unicode.

In [83]:
s = ''
type(s)

str

In [84]:
sys.getsizeof(s)

49

In [85]:
s = 'a'
sys.getsizeof(s)

50

# Strings are sequences

Strings, lists, and tuples are all sequences in Python. Which means, they all:

- Get the length with `len`
- Get an individual item with `[i]`
- Get a slice back with `[start:end+1]` 
- Iterate with a `for` loop
- Have an `.index` method to find the first index with that value
- Have a `.count` method to find how many times an element appears

The differences are:
- Strings contain strings (there is no character type in Python)
- Lists and tuples can contain anything
- Strings and tuples are immutable

In [86]:
s = 'abcd'
s += 'efgh'  # have I changed the string? 

In [88]:
s  # s changed, but it now refers to a new, different string

'abcdefgh'

In [89]:
s = 'abcd'
print(id(s))

s += 'efgh'  # have I changed the string? 
print(id(s))

5214131696
5214071728


In [90]:
# immutable ≠ constant

In [91]:
s[0]

'a'

In [92]:
s[0] = '!'

TypeError: 'str' object does not support item assignment

In [93]:
s = 'aBcDeFgH'

s.lower()  # gives me a new string back

'abcdefgh'

In [94]:
s

'aBcDeFgH'

In [95]:
s.capitalize()

'Abcdefgh'

In [97]:
s.swapcase()  # why does this method exist?

'AbCdEfGh'

In [98]:
# since strings cannot change, and string methods return new strings, we can chain our methods:

s = '   abCDef   '
s.strip().lower()

'abcdef'

In [99]:
s

'   abCDef   '

In [100]:
# the most interesting new way to create strings is the f-string (format string)

x = 100
y = [10, 20, 30]
z = {'a':1, 'b':2}

# in the curly braces, we can have any Python expression
# the value of the expression is turned into a string and added to the resulting f-string
s = f'x = {x}, y = {y}, z = {z}'
print(s)

x = 100, y = [10, 20, 30], z = {'a': 1, 'b': 2}


In [101]:
# as of Python 3.8, we can say this:
s = f'{x=}, {y=}, {z=}'
print(s)

x=100, y=[10, 20, 30], z={'a': 1, 'b': 2}


In [103]:
s = f'{len(y)=}'
print(s)

len(y)=3


# Exercise: Firstlast

1. Write a function, `firstlast`, that takes any sequence (string, list, or tuple) and returns a two-element structure of the same type. 
2. The output's first element will be index 0 from the input, and the final element will be the l